
public class initials {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
System.out.println(
		"  OOOOOOOOOOOOOOOOO       DDDDDDDDDDDDDDDDDD          AAAAAAAAAAAAAAAAA  \n"+     
		" OOOOOOOOOOOOOOOOOOO      DDDDDDDDDDDDDDDDDDD        AAAAAAAAAAAAAAAAAAA \n"+
		"OOOOOOOOOOOOOOOOOOOOO     DDDDDDDDDDDDDDDDDDDD      AAAAAAAAAAAAAAAAAAAAA\n"+
		"OOOOOOOO     OOOOOOOO     DDDDDDD     DDDDDDDDD     AAAAAAAAA   AAAAAAAAA\n"+
		"OOOOOOO       OOOOOOO     DDDDDDD      DDDDDDDD     AAAAAAAA     AAAAAAAA\n"+
		"OOOOOOO       OOOOOOO     DDDDDDD       DDDDDDD     AAAAAAAA     AAAAAAAA\n"+
		"OOOOOOO       OOOOOOO     DDDDDDD       DDDDDDD     AAAAAAAAAAAAAAAAAAAAA\n"+
		"OOOOOOO       OOOOOOO     DDDDDDD       DDDDDDD     AAAAAAAAAAAAAAAAAAAAA\n"+
		"OOOOOOO       OOOOOOO     DDDDDDD      DDDDDDDD     AAAAAAAAAAAAAAAAAAAAA\n"+
		"OOOOOOOO     OOOOOOOO     DDDDDDD     DDDDDDDDD     AAAAAAA       AAAAAAA\n"+
		"OOOOOOOOOOOOOOOOOOOOO     DDDDDDDDDDDDDDDDDDDD      AAAAAAA       AAAAAAA\n"+
		" OOOOOOOOOOOOOOOOOOO      DDDDDDDDDDDDDDDDDDD       AAAAAAA       AAAAAAA\n"+
		"  OOOOOOOOOOOOOOOOO       DDDDDDDDDDDDDDDDDD        AAAAAAA       AAAAAAA\n"
		);

	}

}
